import type { SubjectTopic } from "@/lib/subject-content";

export const gaussianMixtureModelFundamentals: SubjectTopic = {
  slug: "gaussian-mixture-model-fundamentals",
  title: "Gaussian Mixture Model Fundamentals",
  description:
    "Model overlapping data using weighted Gaussian components and soft cluster membership.",
  readTime: "17 min",
  difficulty: "Intermediate",
  tags: ["GMM", "Soft Clustering", "Mixture Weights"],
  learn: {
    opening:
      "A Gaussian Mixture Model assumes the observed data was generated by several Gaussian components. The component that generated a particular example is hidden.",
    sections: [
      {
        title: "Mixture Components",
        paragraphs: [
          "Each component k has a mean μₖ, covariance Σₖ, and mixing weight πₖ. The weight represents the prior share of the dataset associated with that component.",
        ],
        formulas: [
          { label: "Weight conditions", expression: "πₖ ≥ 0 and Σₖ πₖ = 1" },
          { label: "Mixture density", expression: "p(x) = Σₖ πₖ N(x|μₖ,Σₖ)" },
        ],
        visual: {
          src: "/notes/machine-learning/gmm-soft-clustering.png",
          alt: "Overlapping Gaussian components with soft membership probabilities compared with hard K-Means labels",
          width: 1536,
          height: 1024,
          caption:
            "GMM combines weighted component densities and gives uncertain points partial membership in multiple components.",
        },
      },
      {
        title: "Soft Membership",
        paragraphs: [
          "Instead of returning only one cluster ID, GMM calculates a responsibility for every component. Under the current fitted model, each responsibility is the posterior probability that the component generated that example. Responsibilities for one example sum to 1.",
          "A hard label can still be produced by choosing the component with the largest responsibility, but this discards uncertainty information.",
        ],
        formulas: [
          {
            label: "Hard label from GMM",
            expression: "cluster(xᵢ) = arg maxₖ γᵢₖ",
          },
        ],
      },
      {
        title: "GMM vs K-Means",
        paragraphs: [
          "Both divide data into groups, but they represent membership and cluster shape differently.",
        ],
        dataTable: {
          headers: ["Property", "K-Means", "GMM"],
          rows: [
            ["Membership", "Hard", "Soft responsibilities"],
            ["Cluster centre", "Centroid", "Gaussian mean"],
            [
              "Cluster shape",
              "Distance-based spherical bias",
              "Covariance-based ellipses",
            ],
            [
              "Output model",
              "Assignments and centroids",
              "Probability density model",
            ],
            ["Training", "Assign and average", "Expectation-Maximization"],
          ],
        },
      },
      {
        title: "Covariance Choices",
        paragraphs: [
          "A full covariance allows each component to have its own rotated ellipse. Simpler covariance choices use fewer parameters but restrict shape.",
          "A covariance matrix must be symmetric and positive semidefinite. The usual density formula also needs a non-singular positive-definite covariance so its determinant is positive and its inverse exists. Implementations commonly add a small diagonal regularizer for stability.",
        ],
        table: {
          headers: ["Simpler covariance", "Full covariance"],
          rows: [
            ["Fewer parameters", "More parameters"],
            [
              "Faster and more stable with limited data",
              "More flexible component shape",
            ],
            ["Stronger shape assumptions", "Needs enough data per component"],
          ],
        },
      },
      {
        title: "What GMM Assumes",
        points: [
          "The data distribution can be approximated by K Gaussian components.",
          "Examples are treated as independent observations under the model.",
          "Every component has valid weights, means, and covariance parameters.",
        ],
        paragraphs: [
          "A GMM component is not guaranteed to match a meaningful real-world class. Interpretation still requires domain evidence.",
        ],
      },
    ],
    mechanism: {
      title: "How GMM describes one example",
      steps: [
        "Evaluate x under every Gaussian component.",
        "Multiply each density by its mixing weight.",
        "Add contributions to obtain p(x).",
        "Normalize contributions to obtain responsibilities.",
        "Optionally choose the largest responsibility as a hard label.",
      ],
    },
    example: {
      title: "Overlapping speakers",
      body: "Two speakers may have overlapping audio features. GMM can report that one segment has 0.65 responsibility for Speaker A and 0.35 for Speaker B instead of pretending the assignment is certain.",
    },
    misconception:
      "Mixing weights are not the final membership probabilities for a specific example. Responsibilities also depend on that example's component densities.",
  },
  revise: {
    definitionLabel: "Soft Clustering Model",
    compactDefinition: true,
    definition:
      "GMM represents data as a weighted sum of Gaussian components and returns soft component responsibilities.",
    sections: [
      {
        title: "Mixture",
        formulas: [
          { label: "Density", expression: "p(x)=ΣπₖN(x|μₖ,Σₖ)" },
          { label: "Weights", expression: "Σπₖ=1" },
        ],
      },
    ],
    essentialsStyle: "plain",
    essentials: [
      "Each component has π, μ, and Σ.",
      "Mixing weights are non-negative and sum to 1.",
      "Mixture density adds weighted component densities.",
      "Responsibilities give soft membership.",
      "GMM supports covariance-shaped clusters.",
    ],
    followUp: "Why is a mixing weight different from a responsibility?",
  },
  lastMinute: {
    definition: "Several weighted Gaussians combine into one density model.",
    sections: [
      { title: "Component", points: ["π: weight", "μ: centre", "Σ: shape"] },
      {
        title: "Output",
        points: [
          "Density p(x)",
          "Soft responsibilities",
          "Optional hard label",
        ],
      },
    ],
    memoryLine:
      "Weight the component densities, then normalize for membership.",
    cues: [
      "Weights sum to 1.",
      "GMM is soft clustering.",
      "Covariance allows ellipses.",
    ],
    trap: "Do not add component densities without multiplying by their mixing weights.",
  },
};

export const likelihoodLatentVariablesAndResponsibilities: SubjectTopic = {
  slug: "likelihood-latent-variables-and-responsibilities",
  title: "Likelihood, Latent Variables, and Responsibilities",
  description:
    "Use likelihood to fit a GMM and calculate posterior component responsibilities for hidden cluster labels.",
  readTime: "19 min",
  difficulty: "Intermediate",
  tags: ["Likelihood", "Latent Variables", "Responsibilities"],
  learn: {
    opening:
      "GMM observes the feature vectors but not the component that generated each one. The missing component IDs are latent variables, so training must reason about them probabilistically.",
    sections: [
      {
        title: "Latent Component Label",
        paragraphs: [
          "Let zᵢ denote the hidden component for example xᵢ. If zᵢ were known, parameter updates would be simple weighted summaries. Because it is unknown, GMM estimates a distribution over its possible values.",
        ],
      },
      {
        title: "Likelihood and Log-Likelihood",
        paragraphs: [
          "Likelihood treats the observed data as fixed and asks which model parameters make it most plausible. Under independent observations, dataset likelihood multiplies individual mixture densities.",
          "Products of many small densities can underflow numerically. Taking logs changes the product into a sum while preserving the parameter value that maximizes it.",
        ],
        formulas: [
          { label: "Dataset likelihood", expression: "L(θ) = Πᵢ p(xᵢ|θ)" },
          { label: "Log-likelihood", expression: "ℓ(θ) = Σᵢ log p(xᵢ|θ)" },
        ],
      },
      {
        title: "Responsibility Formula",
        paragraphs: [
          "Responsibility γᵢₖ is the posterior probability that component k generated xᵢ under the current parameters. Its numerator is that component's weighted density, and its denominator is the total mixture density.",
        ],
        formulas: [
          {
            label: "Responsibility",
            expression: "γᵢₖ = [πₖN(xᵢ|μₖ,Σₖ)] / [ΣⱼπⱼN(xᵢ|μⱼ,Σⱼ)]",
          },
          { label: "Per-example normalization", expression: "Σₖ γᵢₖ = 1" },
        ],
        visual: {
          src: "/notes/machine-learning/gmm-responsibility-numerical.png",
          alt: "Two weighted Gaussian contributions normalized into component responsibilities",
          width: 1536,
          height: 1024,
          caption:
            "Divide each weighted component density by their sum to obtain responsibilities.",
        },
      },
      {
        title: "Complete Responsibility Numerical",
        paragraphs: [
          "Use the same two-component values as the mixture-density example and normalize their contributions.",
        ],
        problems: [
          {
            title: "Calculate soft membership",
            prompt:
              "For x, let π₁=0.4, N₁(x)=0.10, π₂=0.6, and N₂(x)=0.20. Find γ₁ and γ₂.",
            steps: [
              "Weighted contribution 1 = 0.4(0.10)=0.04.",
              "Weighted contribution 2 = 0.6(0.20)=0.12.",
              "Total mixture density = 0.04+0.12=0.16.",
              "γ₁=0.04/0.16=0.25.",
              "γ₂=0.12/0.16=0.75.",
              "Check: 0.25+0.75=1.",
            ],
            answer:
              "The responsibilities are 0.25 for Component 1 and 0.75 for Component 2.",
          },
        ],
      },
      {
        title: "Log-Likelihood Numerical",
        paragraphs: [
          "Natural logarithms are normally used for likelihood optimization.",
        ],
        problems: [
          {
            title: "Convert product to sum",
            prompt:
              "Two independent observations have mixture densities 0.2 and 0.5. Find their likelihood and natural log-likelihood.",
            steps: [
              "L=0.2(0.5)=0.1.",
              "ℓ=ln(0.2)+ln(0.5)=ln(0.1).",
              "ℓ≈−1.609−0.693=−2.302.",
            ],
            answer:
              "The likelihood is 0.1 and the log-likelihood is approximately −2.302.",
          },
        ],
      },
      {
        title: "Common Numerical Mistakes",
        points: [
          "Using component density without multiplying by πₖ.",
          "Forgetting to divide by the total mixture density.",
          "Normalizing across examples instead of across components for one example.",
          "Adding likelihoods instead of multiplying them.",
          "Multiplying log-likelihood terms instead of adding them.",
        ],
        paragraphs: [
          "A responsibility must lie between 0 and 1, and all component responsibilities for one example must sum to 1.",
        ],
      },
    ],
    mechanism: {
      title: "Responsibility calculation",
      steps: [
        "Evaluate xᵢ under every component density.",
        "Multiply each density by its mixing weight.",
        "Add weighted densities to get p(xᵢ).",
        "Divide each contribution by p(xᵢ).",
        "Check that the responsibilities sum to 1.",
      ],
    },
    example: {
      title: "Uncertain boundary point",
      body: "A point between two overlapping Gaussian groups can receive responsibilities 0.48 and 0.52, correctly showing that its component assignment is uncertain.",
    },
    misconception:
      "Likelihood is not the probability that the parameters are true. It scores how well fixed parameter values explain the observed data.",
  },
  revise: {
    definitionLabel: "Hidden Membership",
    compactDefinition: true,
    definition:
      "Responsibility is the normalized weighted density of one component for one observed example.",
    sections: [
      {
        title: "Essential Formulas",
        formulas: [
          { label: "Likelihood", expression: "Πᵢp(xᵢ)" },
          { label: "Log-likelihood", expression: "Σᵢlog p(xᵢ)" },
          { label: "Responsibility", expression: "πₖNₖ(xᵢ)/ΣⱼπⱼNⱼ(xᵢ)" },
        ],
      },
    ],
    essentialsStyle: "plain",
    essentials: [
      "zᵢ is the hidden component label.",
      "Likelihood multiplies independent observation densities.",
      "Log-likelihood adds log densities.",
      "Responsibilities normalize weighted component densities.",
      "Responsibilities for one example sum to 1.",
    ],
    followUp:
      "Why does GMM use log-likelihood rather than multiplying many densities directly?",
  },
  lastMinute: {
    definition:
      "Responsibility tells how strongly one component explains one example.",
    sections: [
      {
        title: "Order",
        flow: ["Density", "Multiply by π", "Sum", "Divide", "Check total 1"],
        wide: true,
      },
      {
        title: "Likelihood",
        points: ["Product across rows", "Log turns product into sum"],
      },
    ],
    memoryLine:
      "Weighted density divided by total density gives responsibility.",
    cues: [
      "Normalize across components.",
      "Use current parameters.",
      "Log-likelihood can be negative.",
    ],
    trap: "Do not confuse a component's prior weight πₖ with its posterior responsibility γᵢₖ.",
  },
};
