import type { SubjectTopic } from "@/lib/subject-content";

const memoryManagementFundamentals: SubjectTopic = {
  slug: "memory-management-fundamentals",
  title: "Memory Management Fundamentals",
  description:
    "Understand how the OS allocates memory, translates addresses, protects processes, swaps work, and loads code when needed.",
  readTime: "Detailed note",
  difficulty: "Foundation",
  tags: ["Memory", "MMU", "Address Binding"],
  learn: {
    opening:
      "Memory Management is the work the Operating System does to allocate, track, protect, share, and free memory for running programs.",
    sections: [
      {
        title: "Why Memory Management Is Needed",
        paragraphs: [
          "Every running program needs memory for its code, data, stack, and heap. RAM is limited, so several programs must share it safely.",
          "Without memory management, one program could overwrite another program's data, memory could be wasted, and applications could crash.",
        ],
        points: [
          "Give memory to processes when they need it.",
          "Track which regions are free and which are in use.",
          "Keep one process from accessing another process's private memory.",
          "Share selected memory safely when required.",
          "Free memory when a process no longer needs it.",
        ],
      },
      {
        title: "The OS as a Memory Manager",
        paragraphs: [
          "The OS records which process owns each allocated memory region. It also keeps track of free space that can be given to another process.",
          "This separation lets applications such as a browser, code editor, music player, and chat app run at the same time without directly overwriting one another.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-management-allocation.png",
          alt: "Operating System memory manager assigning separate RAM regions to Browser, Code Editor, Music, and Chat processes while tracking free memory.",
          width: 1536,
          height: 1024,
          caption:
            "The OS tracks process ownership and keeps unused RAM available for future allocations.",
        },
      },
      {
        title: "Memory Hierarchy",
        paragraphs: [
          "Computer memory is arranged in levels. Registers and cache are very fast but small. RAM is larger but slower. SSDs and hard disks provide much more storage but are far slower than RAM.",
          "Programs run well when recently used data stays in the faster levels. This works because programs often reuse the same data or access nearby data, a behavior called Locality of Reference.",
        ],
        flow: [
          "CPU Registers - Fastest and Smallest",
          "Cache",
          "RAM",
          "SSD / Hard Disk - Slowest and Largest",
        ],
      },
      {
        title: "Logical and Physical Addresses",
        paragraphs: [
          "A Logical Address, also called a Virtual Address, is the address generated by the CPU while a program is running.",
          "A Physical Address is the real location used to access RAM. The program normally works with logical addresses and does not need to know where its data is physically stored.",
          "For example, a program may use logical address 120 while the translated physical address is 8120.",
        ],
        table: {
          headers: ["Logical Address", "Physical Address"],
          rows: [
            ["Generated by the CPU", "Used to access RAM"],
            [
              "Visible to the running program",
              "Managed by hardware and the OS",
            ],
            [
              "Part of a process's address space",
              "Actual location in main memory",
            ],
          ],
        },
        visual: {
          src: "/notes/operating-systems/memory-logical-physical-mmu.png",
          alt: "CPU sending logical address 120 through the MMU, which translates it to physical address 8120 before RAM is accessed.",
          width: 1536,
          height: 1024,
          caption:
            "The program uses a logical address; the MMU translates it before RAM is accessed.",
        },
      },
      {
        title: "Address Binding",
        paragraphs: [
          "Address Binding is the process of connecting a program's addresses to locations in physical memory.",
          "The binding time decides when those locations become fixed or when they are translated.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-address-binding.png",
          alt: "Comparison of Compile-Time, Load-Time, and Execution-Time address binding from less flexible to more flexible.",
          width: 1536,
          height: 1024,
          caption:
            "Later binding gives the system more freedom to place and move a program in memory.",
        },
      },
      {
        title: "Types of Address Binding",
        dataTable: {
          headers: [
            "Binding time",
            "When the address is chosen",
            "Main limitation",
          ],
          rows: [
            [
              "Compile Time",
              "While the program is compiled",
              "The program must be rebuilt if its location changes",
            ],
            [
              "Load Time",
              "When the program is loaded",
              "The location stays fixed during that run",
            ],
            [
              "Execution Time",
              "While the program is running",
              "Needs hardware translation support",
            ],
          ],
        },
        paragraphs: [
          "Execution-Time Binding is the most flexible method and is common in modern systems. It allows a process to use logical addresses while hardware translates them during every memory access.",
        ],
      },
      {
        title: "Memory Management Unit (MMU)",
        paragraphs: [
          "The Memory Management Unit is hardware that translates logical addresses into physical addresses.",
          "Every translated memory access passes through the MMU. The MMU also helps enforce memory-protection rules, so an invalid access can be stopped instead of reaching another process's memory.",
        ],
        flow: [
          "CPU Generates Logical Address",
          "MMU Translates Address",
          "RAM Receives Physical Address",
          "Data Returns to CPU",
        ],
      },
      {
        title: "Swapping",
        paragraphs: [
          "Swapping temporarily moves an entire process from RAM to secondary storage. The process can be brought back later when it is ready to continue.",
          "This can free RAM for another process, but storage is much slower than memory. Too much swapping can make the system very slow.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-swapping.png",
          alt: "Process P3 being swapped out from RAM to secondary storage and later swapped back into RAM while P1 and P2 remain in memory.",
          width: 1536,
          height: 1024,
          caption:
            "Traditional swapping moves an entire process out of RAM and brings it back later.",
        },
        points: [
          "Swap out: Move a process from RAM to storage.",
          "Swap in: Bring the process back into RAM.",
          "Main benefit: Frees RAM for other work.",
          "Main cost: Storage access is slow.",
        ],
      },
      {
        title: "Modern Note - Swapping vs Paging",
        paragraphs: [
          "Traditional swapping moves an entire process. Modern systems more commonly move individual memory pages instead of moving the whole process.",
          "Paging and page replacement are covered in the next topics. Do not use the terms swapping and paging as if they always mean exactly the same thing.",
        ],
      },
      {
        title: "Dynamic Loading and Dynamic Linking",
        paragraphs: [
          "Dynamic Loading keeps a program module on storage until that module is needed. Dynamic Linking connects a program to a shared library at startup or when a library function is first used.",
          "Both can reduce unnecessary memory use, but they solve different problems.",
        ],
        dataTable: {
          headers: ["Feature", "Dynamic Loading", "Dynamic Linking"],
          rows: [
            ["Main subject", "A program module", "A shared library"],
            [
              "When used",
              "When the module is needed",
              "At startup or when a library symbol is needed",
            ],
            [
              "Main benefit",
              "Avoids loading unused modules",
              "Avoids separate copies of common library code",
            ],
          ],
        },
      },
      {
        title: "Main Trade-Offs",
        paragraphs: [
          "Memory management improves safety and flexibility, but its tracking and translation work also has a cost.",
        ],
        table: {
          headers: ["Benefits", "Costs"],
          rows: [
            ["Safe process separation", "Address translation adds work"],
            ["Flexible use of RAM", "Memory tracking needs OS data structures"],
            [
              "More programs can remain active",
              "Heavy swapping can severely reduce performance",
            ],
            [
              "Code and libraries can be loaded only when needed",
              "Missing or incompatible libraries can stop a program",
            ],
          ],
        },
      },
    ],
    mechanism: {
      title: "Handling a memory access",
      steps: [
        "A running program uses a logical address.",
        "The CPU sends the address to the MMU.",
        "The MMU translates and checks the address.",
        "RAM is accessed using the physical address.",
        "The result is returned to the CPU.",
      ],
    },
    example: {
      title: "Running several applications",
      body: "Chrome, VS Code, Spotify, and Discord can use different logical address spaces. The OS and MMU map their memory to safe physical locations, track ownership, and prevent one process from directly overwriting another process's private memory.",
    },
    misconception:
      "A logical address is not the actual RAM location. It must be translated before physical memory is accessed.",
  },
  revise: {
    definitionLabel: "Overview",
    compactDefinition: true,
    definition:
      "Memory Management efficiently allocates, tracks, protects, and frees memory for programs. It allows multiple processes to run safely while making good use of RAM.",
    sections: [
      {
        title: "Core Concept",
        points: [
          "Allocate memory to processes.",
          "Translate logical addresses into physical addresses.",
          "Load program code when needed.",
          "Free memory when it is no longer needed.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-logical-physical-mmu.png",
          alt: "CPU sending logical address 120 through the MMU, which translates it to physical address 8120 before RAM is accessed.",
          width: 1536,
          height: 1024,
          caption:
            "The MMU translates the program's logical address before RAM is accessed.",
        },
      },
      {
        title: "Memory Hierarchy",
        flow: [
          "Registers - Fastest and Smallest",
          "Cache",
          "RAM",
          "SSD / Hard Disk - Slowest and Largest",
        ],
      },
      {
        title: "Memory Access",
        flow: [
          "CPU generates a Logical Address",
          "MMU translates it",
          "RAM receives the Physical Address",
          "Data returns to the CPU",
        ],
      },
      {
        title: "Swapping",
        steps: [
          "RAM becomes full or memory pressure increases.",
          "The OS selects a process and moves it to storage.",
          "RAM becomes available for other work.",
          "The process is brought back when it is needed.",
        ],
        paragraphs: [
          "Traditional swapping moves an entire process. Modern systems more commonly move individual pages.",
        ],
      },
      {
        title: "Logical vs Physical Address",
        table: {
          headers: ["Logical Address", "Physical Address"],
          rows: [
            ["Generated by the CPU", "Actual location used in RAM"],
            ["Used by the program", "Used after address translation"],
          ],
        },
      },
      {
        title: "Address Binding",
        points: [
          "Compile Time: Address fixed during compilation.",
          "Load Time: Address chosen when the program is loaded.",
          "Execution Time: Address translated while the program runs; common in modern Operating Systems.",
        ],
      },
      {
        title: "MMU and Swapping",
        points: [
          "MMU: Translates Logical Address → Physical Address.",
          "Traditional Swapping: Moves an entire process between RAM and storage.",
          "Swapping frees RAM but storage access is slow.",
        ],
      },
      {
        title: "Dynamic Loading vs Dynamic Linking",
        table: {
          headers: ["Dynamic Loading", "Dynamic Linking"],
          rows: [
            [
              "Loads a program module when needed",
              "Connects a program to a shared library",
            ],
            [
              "Avoids loading unused modules",
              "Allows programs to share common library code",
            ],
            [
              "Used for optional or large program modules",
              "Resolved at startup or when a library function is first needed",
            ],
          ],
        },
      },
    ],
    essentialsStyle: "plain",
    essentials: [
      "Logical Address = Address generated by the CPU.",
      "Physical Address = Actual location used in RAM.",
      "Address Binding can happen at Compile Time, Load Time, or Execution Time.",
      "MMU = Translates Logical Addresses into Physical Addresses.",
      "Memory hierarchy moves from small and fast storage to large and slower storage.",
      "Dynamic Loading loads modules; Dynamic Linking connects shared libraries.",
    ],
    followUp:
      "Why does a program normally use logical addresses instead of physical addresses?",
  },
  lastMinute: {
    definition:
      "Memory Management allocates, manages, protects, and frees memory so multiple programs can run efficiently.",
    sections: [
      {
        title: "Memory Flow",
        flow: ["CPU", "Logical Address", "MMU", "Physical Address", "RAM"],
        wide: true,
      },
      {
        title: "Remember This",
        points: [
          "Memory Hierarchy: Registers → Cache → RAM → SSD / Hard Disk.",
          "Logical Address: Generated by the CPU.",
          "Physical Address: Actual location used in RAM.",
          "Address Binding: Compile Time, Load Time, or Execution Time.",
          "Execution-Time Binding is common in modern Operating Systems.",
          "MMU: Translates Logical Address → Physical Address.",
          "Traditional Swapping: Moves an entire process between RAM and storage.",
        ],
        wide: true,
      },
    ],
    cuesLabel: "Key Points",
    cues: [
      "Memory Management keeps RAM safe and efficient.",
      "Registers and cache are faster and smaller than RAM; storage is larger and slower.",
      "MMU performs address translation.",
      "Swapping temporarily moves an entire process between RAM and storage.",
    ],
    memoryLineLabel: "Remember This",
    memoryLine:
      "The CPU uses a Logical Address; the MMU produces the Physical Address.",
    memoryLineAtEnd: true,
    trap: "Traditional swapping moves an entire process; paging moves individual pages.",
  },
};

const contiguousMemoryAllocation: SubjectTopic = {
  slug: "contiguous-memory-allocation",
  title: "Contiguous Memory Allocation",
  description:
    "Allocate one continuous physical-memory region to each process and understand placement strategies, fragmentation, and compaction.",
  readTime: "Detailed note",
  difficulty: "Intermediate",
  tags: ["Contiguous Allocation", "Fragmentation", "Compaction"],
  learn: {
    opening:
      "Contiguous Memory Allocation gives each process one continuous block of physical memory.",
    sections: [
      {
        title: "Overview",
        paragraphs: [
          "Under contiguous allocation, all physical memory used by one process sits next to itself in one block. The OS chooses a free block, loads the process there, and returns the block when the process finishes.",
          "This model is simple, but free space can be wasted or split into pieces. Modern Operating Systems normally use paging for process memory, but contiguous allocation remains important for understanding fragmentation and placement algorithms.",
        ],
      },
      {
        title: "Why It Matters",
        paragraphs: [
          "When several processes need RAM, the OS must choose where each process will fit. A poor choice may leave small unusable spaces and prevent later allocations even when the total free memory looks sufficient.",
        ],
        points: [
          "Choose a free region large enough for the process.",
          "Keep every process inside its assigned region.",
          "Track allocated blocks and free holes.",
          "Reuse a block after its process finishes.",
          "Limit wasted space and expensive memory movement.",
        ],
      },
      {
        title: "Core Concept",
        paragraphs: [
          "A process receives one base address and one continuous range of memory. Its code, data, heap, and stack must fit inside that range under this allocation model.",
          "Fixed Partitioning and Variable Partitioning are the two common forms.",
        ],
        visual: {
          src: "/notes/operating-systems/contiguous-fixed-variable.png",
          alt: "Fixed Partitioning with permanent RAM boundaries and internal waste compared with Variable Partitioning using differently sized contiguous process regions.",
          width: 1536,
          height: 1024,
          caption:
            "Fixed partitions keep permanent boundaries; variable partitions are created to match process sizes.",
        },
      },
      {
        title: "Memory Protection with Base and Limit Registers",
        paragraphs: [
          "A simple contiguous system can protect each process with a Base Register and a Limit Register.",
          "The Base Register stores the first physical address of the process. The Limit Register stores the size of the allowed address range.",
          "For each logical address, hardware checks that the address is smaller than the limit. It then adds the base to form the physical address. An address outside the limit causes a protection fault.",
        ],
        flow: [
          "Logical Address",
          "Check Address < Limit",
          "Add Base Address",
          "Physical Address",
        ],
      },
      {
        title: "Fixed Partitioning",
        paragraphs: [
          "RAM is divided into a fixed number of partitions before processes are loaded. The partitions may be equal or unequal in size, but their boundaries do not change while the system is using that layout.",
          "Each partition holds at most one process. If a process is smaller than its partition, the remaining space inside that partition cannot be given to another process.",
        ],
        table: {
          headers: ["Benefits", "Limitations"],
          rows: [
            ["Simple and fast allocation", "Unused space inside a partition"],
            ["Easy memory tracking", "One process per partition"],
            [
              "Predictable boundaries",
              "Process count is limited by partition count",
            ],
          ],
        },
      },
      {
        title: "Variable Partitioning",
        paragraphs: [
          "The OS creates a partition when a process arrives and sizes it according to that process's memory request.",
          "This reduces the large internal waste found in fixed partitions. However, when processes enter and leave, free spaces appear between allocated blocks. These spaces are called holes and can cause External Fragmentation.",
        ],
        table: {
          headers: ["Benefits", "Limitations"],
          rows: [
            [
              "Partition closely matches process size",
              "Free holes appear over time",
            ],
            [
              "Usually better memory use than fixed partitions",
              "Finding a suitable hole takes work",
            ],
          ],
        },
      },
      {
        title: "Choosing a Free Block",
        paragraphs: [
          "Variable Partitioning may have several free holes. The placement strategy decides which suitable hole receives the next process.",
        ],
        visual: {
          src: "/notes/operating-systems/contiguous-allocation-strategies.png",
          alt: "First Fit and Best Fit selecting a 250 KB hole while Worst Fit selects a 400 KB hole for a 200 KB process.",
          width: 1536,
          height: 1024,
          caption:
            "The same request can be placed differently depending on the selected strategy.",
        },
      },
      {
        title: "First Fit",
        paragraphs: [
          "First Fit scans free blocks from the beginning and selects the first block large enough for the process.",
          "For holes of 100 KB, 250 KB, and 400 KB, a 200 KB process is placed in the 250 KB hole because it is the first suitable choice.",
        ],
        points: [
          "Usually fast because the search can stop early.",
          "Simple to implement.",
          "May leave small holes near the beginning of memory.",
        ],
      },
      {
        title: "Best Fit",
        paragraphs: [
          "Best Fit selects the smallest free block that is still large enough for the process.",
          "For the same example, it selects 250 KB and leaves 50 KB. It reduces the leftover from that one allocation, but repeated use may create many tiny holes.",
        ],
        points: [
          "Checks all holes unless the free list is specially organized.",
          "Minimizes the immediate leftover for one request.",
          "Does not guarantee the best long-term memory use.",
        ],
      },
      {
        title: "Worst Fit",
        paragraphs: [
          "Worst Fit selects the largest available free block.",
          "For the same example, it uses the 400 KB hole and leaves 200 KB. The goal is to leave a large remainder that may still serve another request.",
        ],
        points: [
          "Usually requires searching all holes.",
          "Preserves a larger remainder after the current allocation.",
          "Often performs poorly and is rarely the default choice.",
        ],
      },
      {
        title: "Allocation Strategy Comparison",
        dataTable: {
          headers: ["Strategy", "Selection rule", "Main trade-off"],
          rows: [
            [
              "First Fit",
              "First suitable hole",
              "Fast search, but may crowd the start of memory",
            ],
            [
              "Best Fit",
              "Smallest suitable hole",
              "Small immediate remainder, but may create tiny holes",
            ],
            [
              "Worst Fit",
              "Largest available hole",
              "Large remainder, but often weak overall use",
            ],
          ],
        },
        paragraphs: [
          "No strategy always produces the best result. The outcome depends on the order and sizes of process requests.",
        ],
      },
      {
        title: "Internal and External Fragmentation",
        paragraphs: [
          "Fragmentation means memory exists but some of it cannot be used effectively.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-fragmentation.png",
          alt: "Internal Fragmentation showing 30 KB unused inside a 100 KB allocated partition and External Fragmentation showing 60 KB free across separated holes that cannot hold a 50 KB process.",
          width: 1536,
          height: 1024,
          caption:
            "Internal waste is inside an allocation; external waste is spread between allocations.",
        },
      },
      {
        title: "Internal Fragmentation",
        paragraphs: [
          "Internal Fragmentation is unused space inside an allocated block.",
          "If a 70 KB process receives a 100 KB fixed partition, 30 KB remains unused inside that partition. Another process cannot use it while the partition is allocated.",
        ],
        points: [
          "Common with Fixed Partitioning.",
          "The wasted space is inside the allocated region.",
        ],
      },
      {
        title: "External Fragmentation",
        paragraphs: [
          "External Fragmentation happens when free memory is split into separate holes between allocated regions.",
          "For example, holes of 20 KB, 15 KB, and 25 KB contain 60 KB in total. A 50 KB process still cannot be allocated because no one continuous 50 KB hole exists.",
        ],
        points: [
          "Common with Variable Partitioning.",
          "Enough total memory may exist, but not as one continuous block.",
        ],
      },
      {
        title: "Coalescing",
        paragraphs: [
          "Coalescing joins adjacent free holes into one larger free hole when memory is released. It does not move active processes.",
          "For example, if a 25 KB process ends between free holes of 20 KB and 30 KB, the three adjacent free regions can become one 75 KB hole.",
        ],
        table: {
          headers: ["Coalescing", "Compaction"],
          rows: [
            [
              "Joins only adjacent free holes",
              "Combines separated holes by moving processes",
            ],
            ["Does not move active processes", "Moves active processes"],
            ["Usually low overhead", "Expensive memory-copying work"],
          ],
        },
      },
      {
        title: "Compaction",
        paragraphs: [
          "Compaction moves allocated processes together so separate free holes become one large continuous block.",
          "It removes External Fragmentation, but copying process memory takes time and may pause work. Compaction also requires addresses to be relocated safely, so execution-time address binding is needed.",
        ],
        visual: {
          src: "/notes/operating-systems/memory-compaction.png",
          alt: "RAM before compaction with free holes between P1, P2, and P3, and RAM after compaction with the processes together followed by one large free block.",
          width: 1536,
          height: 1024,
          caption:
            "Compaction joins scattered free holes, but moving process memory is expensive.",
        },
        points: [
          "Combines free holes into one large block.",
          "Removes External Fragmentation, not Internal Fragmentation.",
          "Requires relocation support.",
          "Adds CPU and memory-copying overhead.",
        ],
      },
      {
        title: "Main Trade-Offs",
        paragraphs: [
          "Contiguous allocation is easy to understand and manage, but fragmentation and process movement make it unsuitable as the main process-memory method in most modern systems.",
        ],
        table: {
          headers: ["Strengths", "Weaknesses"],
          rows: [
            [
              "Simple address calculation",
              "Internal or External Fragmentation",
            ],
            [
              "Simple protection with Base and Limit",
              "A process needs one large continuous block",
            ],
            ["First Fit can allocate quickly", "Compaction is expensive"],
          ],
        },
      },
    ],
    mechanism: {
      title: "Allocating a process",
      steps: [
        "A process requests a continuous amount of memory.",
        "The OS searches the free-hole list using a placement strategy.",
        "A suitable hole is selected and divided if it is larger than the request.",
        "The OS records the process's Base and Limit values.",
        "When the process finishes, its block becomes a free hole.",
      ],
    },
    example: {
      title: "Allocating a 200 KB process",
      body: "With free holes of 100 KB, 250 KB, and 400 KB, First Fit and Best Fit choose the 250 KB hole. Worst Fit chooses the 400 KB hole. The selected strategy changes the free holes left for future processes.",
    },
    misconception:
      "Best Fit does not always give the best long-term memory use. It can create many small holes that are difficult to reuse.",
  },
  revise: {
    definitionLabel: "Overview",
    compactDefinition: true,
    definition:
      "Contiguous Memory Allocation gives each process one continuous physical-memory block. The OS selects a suitable free block using a placement strategy.",
    sections: [
      {
        title: "Core Concept",
        paragraphs: [
          "Each process occupies one continuous block. When the process finishes, that block becomes a free hole that another process may use.",
        ],
        visual: {
          src: "/notes/operating-systems/contiguous-fixed-variable.png",
          alt: "Fixed Partitioning with permanent RAM boundaries and internal waste compared with Variable Partitioning using differently sized contiguous process regions.",
          width: 1536,
          height: 1024,
          caption:
            "Fixed partitions keep permanent boundaries; variable partitions are created for process sizes.",
        },
      },
      {
        title: "Fixed vs Variable Partitioning",
        table: {
          headers: ["Fixed Partitioning", "Variable Partitioning"],
          rows: [
            [
              "Partition boundaries are fixed",
              "Partitions are created dynamically",
            ],
            [
              "One process occupies one partition",
              "A process receives the requested block size",
            ],
            [
              "Mainly causes Internal Fragmentation",
              "Mainly causes External Fragmentation",
            ],
          ],
        },
      },
      {
        title: "Memory Allocation Strategies",
        dataTable: {
          headers: ["Strategy", "Selection rule", "Main point"],
          rows: [
            [
              "First Fit",
              "First suitable free block",
              "Usually the fastest search",
            ],
            [
              "Best Fit",
              "Smallest suitable free block",
              "May create tiny holes",
            ],
            [
              "Worst Fit",
              "Largest available free block",
              "Leaves a larger remainder",
            ],
          ],
        },
      },
      {
        title: "Internal vs External Fragmentation",
        table: {
          headers: ["Internal Fragmentation", "External Fragmentation"],
          rows: [
            [
              "Waste inside an allocated block",
              "Free memory scattered between allocated blocks",
            ],
            [
              "Common with Fixed Partitioning",
              "Common with Variable Partitioning",
            ],
          ],
        },
      },
      {
        title: "Coalescing vs Compaction",
        table: {
          headers: ["Coalescing", "Compaction"],
          rows: [
            [
              "Joins adjacent free holes",
              "Moves processes to join separated holes",
            ],
            ["Does not move active processes", "Requires relocation support"],
            ["Lower overhead", "Higher copying overhead"],
          ],
        },
      },
    ],
    essentialsStyle: "plain",
    essentials: [
      "Fixed Partitioning → Fixed boundaries and mainly Internal Fragmentation.",
      "Variable Partitioning → Dynamic boundaries and mainly External Fragmentation.",
      "First Fit → First suitable block.",
      "Best Fit → Smallest suitable block.",
      "Worst Fit → Largest available block.",
      "Coalescing joins adjacent holes; Compaction moves processes to join separated holes.",
    ],
    followUp:
      "Why can enough total free memory still fail to satisfy a process request?",
  },
  lastMinute: {
    definition:
      "Contiguous Memory Allocation gives each process one continuous physical-memory block.",
    sections: [
      {
        title: "Memory Layout",
        flow: ["RAM", "Process A", "Process B", "Free Memory", "Process C"],
        wide: true,
      },
      {
        title: "Remember This",
        points: [
          "Fixed Partitioning: Fixed boundaries; mainly causes Internal Fragmentation.",
          "Variable Partitioning: Dynamic boundaries; mainly causes External Fragmentation.",
          "First Fit: First suitable free block.",
          "Best Fit: Smallest suitable free block.",
          "Worst Fit: Largest available free block.",
        ],
        wide: true,
      },
    ],
    cuesLabel: "Key Points",
    cues: [
      "Fixed Partitioning → Mainly Internal Fragmentation.",
      "Variable Partitioning → Mainly External Fragmentation.",
      "Internal = Waste inside an allocation.",
      "External = Free holes between allocations.",
      "Coalescing joins adjacent holes; Compaction moves processes to join separated holes.",
      "First Fit is usually the fastest of these three simple searches.",
      "Best Fit may create tiny holes; Worst Fit uses the largest hole.",
    ],
    memoryLineLabel: "Remember This",
    memoryLine: "Internal is inside. External is between.",
    memoryLineAtEnd: true,
    trap: "Best Fit can leave tiny holes; its name does not mean it is always best.",
  },
};

export { contiguousMemoryAllocation, memoryManagementFundamentals };
